// auth
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// consumption list
export const GET_CONSUMPTION_LIST = 'GET_CONSUMPTION_LIST';
export const SAVE_CONSUMPTION_LIST = 'SAVE_CONSUMPTION_LIST';
export const UPDATE_CONSUMPTION_QUANTITY = 'UPDATE_CONSUMPTION_QUANTITY';
export const UPDATE_CONSUMPTION_CALORIES = 'UPDATE_CONSUMPTION_CALORIES';
export const DELETE_CONSUMPTION = 'DELETE_CONSUMPTION';
export const CLEAR_CONSUMPTIONS = 'CLEAR_CONSUMPTIONS';
